name: axcorsrmri
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - python==3.10
  - pip
  - pip:
    - -r file:requirements.txt
